### ISSUE TITLE
Why is it light mode when my browser is dark mode

### ISSUE THREAD

**Issue by dredshep** [pkrasicki/lemmy-modern-ui-theme-addon#3] opened 2023-07-03 12:48 UTC
browser is dark mode

lemmy preferences are set to dark

yet:

![image](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/78047001/3f8a00eb-4b38-4779-83a5-bfc618e34e92)

**Comment by pkrasicki** [comment] 2023-07-03 15:45
It seems that sometimes Lemmy loads a light theme first and then switches to dark theme later. The addon's theme detection detects the light theme and applies styles for it. The result is a mix of the default darkly theme (which was later applied) and the light theme styles from the addon.

I'm not sure how to fix this yet, but I will look into it.

**Comment by dredshep** [comment] 2023-07-03 16:36
I see it go from dark to light though so it should be detecting the dark one that it applies onto. Since it's not stylus but an extension I have some trouble debugging cuz I'd have to build it and I'm too lazy to build it.

Nevermind I remember there's a release. I just don't wanna add URLs. Seems simple enough to test. Will do that later.

**Comment by pkrasicki** [comment] 2023-07-03 17:28
There are some docs about debugging. It's not really working for me right now and the code is minified anyway. But maybe you will have some luck: https://extensionworkshop.com/documentation/develop/debugging/#debugging-content-scripts.

In my case I added 2 console logs like this:
```
const applyTheme = (styleSheetsArray) =>
{
	const isLightTheme = styleSheetsArray.some((sheet) =>
	{
		const url = new URL(sheet.href);
		const themeNameRegex = /\/litely.*\.css$/;
		const isLitely = themeNameRegex.test(url.pathname);
		const mediaArray = [...sheet.media];
		const isActive = mediaArray.every((mediaString) => matchMedia(mediaString).matches);

		return isLitely && isActive;
	});

	console.log('isLightTheme', isLightTheme);
	const themeStyles = isLightTheme ? lightTheme : darkTheme;

	const style = document.createElement("STYLE");
	style.innerText = themeStyles;
	document.body.prepend(style);
};

const main = () =>
{
	const styleSheetsArray = [...document.styleSheets];
	console.log('styleSheetsArray', styleSheetsArray);
```

Then I built the addon.

![lemmy-theme-loading-issue](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/49721209/3b4b1565-dce6-4615-8ff1-9e6850948374)

When the bug happens you can see that `litely.css` is on the list of loaded stylesheets, so the variable `isLightTheme` is set to true. When after that you manually run `document.styleSheets` in browser's console you can see that `litely.css` is no longer there.

We need a better theme detection. Maybe it should somehow react on stylesheet changes?

**Comment by pkrasicki** [comment] 2024-04-19 15:12
Does this still happen in Lemmy 0.19.3? I don't see this behavior anymore, so maybe it was fixed by the devs.

**Comment by pkrasicki** [comment] 2024-10-05 14:06
I think this problem was caused by a bug in Lemmy 0.18.x and doesn't happen in current Lemmy versions. So I will close this.

**Closed as completed by pkrasicki** 2024-10-05 14:06 UTC
Labels: bug
