### ISSUE TITLE
Dark theme bug: Black text on markdown tables

### ISSUE THREAD

**Issue by sevonj** [pkrasicki/lemmy-modern-ui-theme-addon#8] opened 2024-01-30 15:33 UTC
Post:
```
| Column | Column | Column    |
| ------ | ------ | --------- |
| Text   | Text   | Also text |
```
Result:
![image](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/100710152/54c8772b-d1b4-4d12-9177-49cb6218008c)

Tested on firefox.

**Comment by pkrasicki** [comment] 2024-02-04 17:00
I tested this in Lemmy versions 0.18.5, 0.19.2 and 0.19.3, but couldn't reproduce the issue. Which version of Lemmy did you use and how often does it happen?

Does it happen everywhere or only on some specific part of the page (like a comment or post preview)?

**Comment by sevonj** [comment] 2024-02-04 18:15
Sorry, I was a bit tired when I filed this issue and completely forgot the _addon_ part. 

Lemmy-UI: 0.19.3
Tested Browsers: Firefox, Chromium
Platform: Fedora 39

The important bit:
Theme is installed on the instance, and _not the addon_.
I tested the addon now, and that way it actually works.

It breaks again when I set my theme to modern in user settings. So I guess the white font came from darkly, which the instance had loaded.

Affects posts and comments alike, I guess all markdown.

**Comment by pkrasicki** [comment] 2024-02-04 20:11
The modern-dark theme is based on `darkly.css` (it imports it from your folder). So if that file is available and darkly itself doesn't have this problem, then everything should work fine.

Could you open your browser's dev tools and look at the table's styles in the inspector? The CSS variable `--bs-table-color` should be responsible for text color in tables. When using the addon for me it's the same as `--bs-emphasis-color`, which is just white.

![lemmy-table-css](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/49721209/d5374e8e-ab2c-4f08-91cd-86ef599f05ed)

![lemmy-table-css2](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/49721209/79cb4252-754e-4a05-b6d6-e8e7e62bc6c3)


It should be using the emphasis color by default: https://github.com/LemmyNet/lemmy-ui/blob/main/src/assets/css/themes/darkly.css#L1861

But that can be either black or white:
https://github.com/LemmyNet/lemmy-ui/blob/main/src/assets/css/themes/darkly.css#L135
https://github.com/LemmyNet/lemmy-ui/blob/main/src/assets/css/themes/darkly.css#L86

I don't know why darkly has two sets of colors, but maybe something went wrong there.

**Comment by sevonj** [comment] 2024-02-05 11:32
![image](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/100710152/77409cd7-c450-42fa-8ea5-b48877381855)
Yup, it's #000

It's definitely something to do with dark / light colors (indeed, why does darkly have a light mode?).

I recreated the bug in stock darkly by swapping the names:
![image](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/100710152/b3908b89-7ab1-4460-a830-a64b09446be5)

**Comment by pkrasicki** [comment] 2024-02-06 00:07
The issue seemed to affect all tables, even the ones in /modlog and /instances. Code blocks were also messed up - they had a white background even in dark theme.

![lemmy-code-blocks-bug](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/49721209/0734483c-a223-484c-a175-70152c9cae2e)

I fixed the tables and the code blocks and created a new release. Please test it and let me know if it's fixed.

### The cause:
From what I can tell, in versions 0.18.x the `data-bs-theme` attribute was always set to `light`, no matter what theme was used. This is why some of the backgrounds were too bright in darkly (and my theme fixed that).

![lemmy-data-bs-theme](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/49721209/d948d623-f3d3-4085-b83f-e97319424cfd)

There is some code that is supposed to determine the right value for `data-bs-theme`: https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/utils/browser/data-bs-theme.ts#L12. But apparently it was never used to actually set the value of that attribute. According to that code, `data-bs-theme` should be set to `dark` only when one of Lemmy's default dark themes is used (or when it's set to automatic based on system theme). Custom themes are not taken into account.

Some time after the 0.18.5 release, they added this: https://github.com/LemmyNet/lemmy-ui/commit/dd3842655a295370505485e14aeab46652e32d99. That's why now `data-bs-theme` attribute is actually set to `dark` whenever one of those default dark themes is used. They must have also changed the colors for when the attribute is set to `light`.

The addon was also affected by this problem, but only when an instance uses a custom theme (which is rare). Otherwise the attribute is set correctly and everything just works.

The code blocks are a different issue. Their color is supposed to depend on user's system theme settings. So if an instance uses a dark theme, but the user's system uses light theme, they will have white code blocks. You can see this on public instances when you have the addon disabled.

**Comment by sevonj** [comment] 2024-02-06 11:40
Nice, I'll see them update the theme and report back.

**Comment by sevonj** [comment] 2024-02-06 12:09
Check this out: https://suppo.fi/post/1136393

**Comment by pkrasicki** [comment] 2024-02-06 14:23
Thanks for testing! Looks like it's fixed now, so I will close the issue. If you find more problems, feel free to open a new one.

**Closed as completed by pkrasicki** 2024-02-06 14:23 UTC
